apiVersion: v1
kind: Pod

metadata:
  name: studentapp-pod

spec:
  containers:
    - name: studentapp-container
      image: anandaditya955/studentapp:v2

      ports:
        - containerPort: 5978

      envFrom:
        - configMapRef:
            name: aditya-configure

        - secretRef:
            name: student-secret

      env:
        - name: FLASK_ENV
          value: "production"

        - name: APP_PORT
          value: "5978"

      volumeMounts:
        - name: student-storage
          mountPath: /app/data

  volumes:
    - name: student-storage
      emptyDir: {}