apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: studentapp-pvc
  namespace: prod-ns

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 500Mi
      